const configItems = {
	'CIC (New)::Event': 'Event Details',
	'CIC (New)::Flow': 'Flow Condition\nJudgement Rule\nSet Specified Members\nQuery\nOutbound Message (Process)',
	'CIC (New)::Config Data': 'Config Data',
	'CSC(New)::Service Type Management': 'Service Type Name',
	'CSC(New)::Workflow Template': 'Assignment Process',
	'CSC(New)::Activity Rule': 'Dispatch Rule',
	'CSC(New)::Activity Template': 'Activity Name',
	'CSC(New)::Closure Reason': 'Event Name',
	'CSC(New)::Configuration Parameter': 'Configuration Parameter',
	'CPC (New)::Assessment': 'Assessment',
	'CPC (New)::Bundle Offer': 'Base Information\nLifeCycle Apply\nOffer Version\nOffer Group (bundle level)\nBundle Member\nBundle Restrict Rule\nBundle Member Group\nOffer Attribute\nOffer Relationship\nSales Condition\nPrice For Tariff\nAdvanced Sales Condition\nQuantity Limit\nSales Permissions\nNotification Configuration\nAgreement Restrict',
	'CPC (New)::Main Offer': 'Base Information\nLifecycle Type\nOffer Version\nProduct Specification\nOffer Group\nSales Condition\nOffer Relationship\nPrice for Tariff\nOffer Attribute\nPrice for OTC\nAdvanced Sales Condition\nSales Permissions\nNotification Configuration\nQuantity Limit\nAgreement Restrict',
	'CPC (New)::Additional Offer': 'Base Information\nLifecycle Type\nOffer Attribute\nProduct Specification\nSales Condition\nPrice for Tariff\nPrice for OTC\nOffer Relationship\nBelong in Offer Group\nPackage\nQuantity Limit\nSales Permissions\nNotification Configuration\nAgreement Restrict',
	'CPC (New)::Goods': 'Base Information\nProduct Attribute Feature\nSales Condition\nSales Permissions',
	'CPC (New)::Related Product': 'Base Information\nProduct Attribute Feature',
	'CPC (New)::Main Product': 'Base Information\nProduct Attribute Feature\nPassword Generation Rule\nApply Number & SIM Config',
	'CPC (New)::Sales Category': 'Bundle Name',
	'CPC (New)::Tariff Plan': 'Tariff Plan',
	'CPC (New)::Price Plan': 'Price Plan',
	'CPC (New)::OTC Price Plan / Payment Decision': 'Order Action, Rule, Condition',
	'CPC (New)::Agreement': 'Base Information, Agreement Object, Penalty, Action Rule',
	'CPC (New)::Promotion Manager View': 'Base Information, Sales Condition, Sales Permission, Promotion Attribute, Promotion Member, Promotion Bonus',
	'CPC (New)::TCOP': 'TCOP mapping',
	'CPC (New)::Offer Group': 'Base Information, Member List, Group Tag, Group Relationship, Group Sales Rule, Attached Offer, Offer Default Select, Offer Hidden Mode',
	'CPC (New)::SKU/SPU': 'SPU information, SPU Attribute Group, SKU Attribute, SKU Information.',
	'CPC (New)::Zone': 'Zone Map, zone detail, zone value',
	'CPC (New)::RLC': 'Rule',
	'CPC (New)::UT': 'Per Offer',
	'CPC (New)::Time Limit Rule Management': 'Quantity limit by subscriber/order/instance',
	'CPC (New)::CRM Rule Action': 'Rule',
	'CPC (New)::CPC Business Rule': 'Specific subscription rule for bundle/main offer',
	'CPC (New)::Tag Manager View': 'Offer Group Tag',
	'JNC (New)::Balance / Account Item Type': 'To create a new account item type. To filled up account item type name, account balance type, adjust catg, etc',
	'JNC (New)::Consumption Type': 'To create a new consumption type that tie to the account item type. This consumption type will be used by CPC to create price plan/tarrif plan/otc',
	'JNC (New)::Merge': "Bill format merging is to define the account item type's charge section in bill. E.g monthly charge, other charge, discounts",
	'JNC (New)::Tax code S8/NT': 'To configure the tax code of the account item type. Tax code for ST is default, no need to configure. NT and S8 need to configure',
	'JNC (New)::Apportion Recurring and Apportion Discount': 'To configure the apportion rule for discount/rebate/waiver',
	'JNC (New)::Adjustment mapping rule': 'To configure the adjustment mapping rule for journal (BA and UBA)',
	'JNC (New)::GL mapping rule': 'To configure the GL mapping rule for journal (BE, UBE, BUE, OCR)',
	'JNC (New)::Journal rule condition': 'To configure the condition for discount/rebate/waiver without journal UBE and BUE',
	'JNC (New)::Apportion rule': 'To configure the bundle splitting',
	'JNC (New)::Fair apportion object': 'To configure fair apportion object',
	'JNC (New)::Fair apportion catalog': 'To configure fair apportion catalog',
	'JNC (New)::Journal rule for one time charge': 'To configure journal rule for OTC payment type',
	'JNC (New)::Exclusion of Account Item Type from normal journal workflow': 'To configure the condition to exclude the Account Item Type from the Account Attribute validation againts the Cost Center and Profit Center mapping rules',
	'JNC (New)::Bill template': 'To configure bill template for bill presentment',
	'JNC (New)::UT': 'UT',
	'JNC (New)::Account Item Group': 'To update existing Account Item Group\nTo create new Account Item Group'
};

const configItemBreakdowns = {
	'CIC (New)::Event': 'Event Details - 0.02',
	'CIC (New)::Flow': 'Flow Condition - 0.02\nJudgement Rule - 0.01\nSet Specified Members - 0.02\nQuery - 0.01\nOutbound Message (Process) - 0.04',
	'CIC (New)::Config Data': 'Config Data - 0.01',
	'CSC(New)::Service Type Management': 'Service Type Name - 0.02',
	'CSC(New)::Workflow Template': 'Assignment Process - 0.01',
	'CSC(New)::Activity Rule': 'Dispatch Rule - 0.01',
	'CSC(New)::Activity Template': 'Activity Name - 0.01',
	'CSC(New)::Closure Reason': 'Event Name - 0.01',
	'CSC(New)::Configuration Parameter': 'Configuration Parameter - 0.01',
	'CPC (New)::Assessment': 'Assessment - 0.042',
	'CPC (New)::Bundle Offer': 'Base Information / LifeCycle Apply / Offer Version - 0.002\nOffer Group (bundle level) - 0.01\nBundle Member / Bundle Restrict Rule - 0.021\nBundle Member Group - 0.063\nOffer Attribute - 0.002\nOffer Relationship - 0.125\nSales Condition - 0.01\nPrice For Tariff - 0.002\nAdvanced Sales Condition - 0.002\nQuantity Limit - 0.004\nSales Permissions - 0.01\nNotification Configuration - 0.002\nAgreement Restrict - 0.002',
	'CPC (New)::Main Offer': 'Base Information / Lifecycle Type / Offer Version - 0.002\nProduct Specification - 0.01\nOffer Group - 0.063\nSales Condition - 0.01\nOffer Relationship - 0.031\nPrice for Tariff - 0.002\nOffer Attribute - 0.002\nPrice for OTC - 0.002\nAdvanced Sales Condition - 0.002\nSales Permissions - 0.01\nNotification Configuration - 0.002\nQuantity Limit - 0.004\nAgreement Restrict - 0.002',
	'CPC (New)::Additional Offer': 'Base Information / Lifecycle Type - 0.002\nOffer Attribute - 0.002\nProduct Specification - 0.01\nSales Condition - 0.01\nPrice for Tariff - 0.002\nPrice for OTC - 0.002\nOffer Relationship - 0.01\nBelong in Offer Group - 0.002\nPackage - 0.01\nQuantity Limit - 0.002\nSales Permissions - 0.01\nNotification Configuration - 0.002\nAgreement Restrict - 0.002',
	'CPC (New)::Goods': 'Base Information - 0.002\nProduct Attribute Feature - 0.002\nSales Condition - 0.01\nSales Permissions - 0.01',
	'CPC (New)::Related Product': 'Base Information - 0.002\nProduct Attribute Feature - 0.002',
	'CPC (New)::Main Product': 'Base Information - 0.002\nProduct Attribute Feature - 0.002\nPassword Generation Rule - 0.002\nApply Number & SIM Config - 0.002',
	'CPC (New)::Sales Category': 'Bundle Name - 0.002',
	'CPC (New)::Tariff Plan': 'Tariff Plan - 0.01',
	'CPC (New)::Price Plan': 'Price Plan - 0.042',
	'CPC (New)::OTC Price Plan / Payment Decision': 'Order Action, Rule, Condition - 0.031',
	'CPC (New)::Agreement': 'Base Information, Agreement Object, Penalty, Action Rule - 0.021',
	'CPC (New)::Promotion Manager View': 'Base Information, Sales Condition, Sales Permission, Promotion Attribute, Promotion Member, Promotion Bonus - 0.01',
	'CPC (New)::TCOP': 'TCOP mapping - 0.002',
	'CPC (New)::Offer Group': 'Base Information, Member List, Group Tag, Group Relationship, Group Sales Rule, Attached Offer, Offer Default Select, Offer Hidden Mode - 0.054',
	'CPC (New)::SKU/SPU': 'SPU information, SPU Attribute Group, SKU Attribute, SKU Information. - 0.021',
	'CPC (New)::Zone': 'Zone Map, zone detail, zone value - 0.021',
	'CPC (New)::RLC': 'Rule - 0.125',
	'CPC (New)::UT': 'Per Offer - 0.01',
	'CPC (New)::Time Limit Rule Management': 'Quantity limit by subscriber/order/instance - 0.021',
	'CPC (New)::CRM Rule Action': 'Rule - 0.021',
	'CPC (New)::CPC Business Rule': 'Specific subscription rule for bundle/main offer - 0.02',
	'CPC (New)::Tag Manager View': 'Offer Group Tag - 0.02',
	'JNC (New)::Balance / Account Item Type': 'To create a new account item type. To filled up account item type name, account balance type, adjust catg, etc',
	'JNC (New)::Consumption Type': 'To create a new consumption type that tie to the account item type. This consumption type will be used by CPC to create price plan/tarrif plan/otc',
	'JNC (New)::Merge': "Bill format merging is to define the account item type's charge section in bill. E.g monthly charge, other charge, discounts",
	'JNC (New)::Tax code S8/NT': 'To configure the tax code of the account item type. Tax code for ST is default, no need to configure. NT and S8 need to configure',
	'JNC (New)::Apportion Recurring and Apportion Discount': 'To configure the apportion rule for discount/rebate/waiver',
	'JNC (New)::Adjustment mapping rule': 'To configure the adjustment mapping rule for journal (BA and UBA)',
	'JNC (New)::GL mapping rule': 'To configure the GL mapping rule for journal (BE, UBE, BUE, OCR)',
	'JNC (New)::Journal rule condition': 'To configure the condition for discount/rebate/waiver without journal UBE and BUE',
	'JNC (New)::Apportion rule': 'To configure the bundle splitting',
	'JNC (New)::Fair apportion object': 'To configure fair apportion object',
	'JNC (New)::Fair apportion catalog': 'To configure fair apportion catalog',
	'JNC (New)::Journal rule for one time charge': 'To configure journal rule for OTC payment type',
	'JNC (New)::Exclusion of Account Item Type from normal journal workflow': 'To configure the condition to exclude the Account Item Type from the Account Attribute validation againts the Cost Center and Profit Center mapping rules',
	'JNC (New)::Bill template': 'To configure bill template for bill presentment',
	'JNC (New)::UT': 'UT',
	'JNC (New)::Account Item Group': 'To update existing Account Item Group - 0.02\nTo create new Account Item Group'
};
